### ISSUE TITLE
Where can I find uniform_align_data?

### ISSUE THREAD

**Issue by Zi-hao-Wei** [xbdxwyh/mocose#1]
Hi, I am trying to reproduce the the result of mocose and I find that you use uniform_align_data, which I didn't find in the SentVal.zip. 
![QQ截图20220317120304](https://user-images.githubusercontent.com/53633429/158843737-d8266721-67f7-473e-a87f-945cca73fa79.png)

**Comment by AdamRain** [comment]
Hi, we have updated the missing files.
The file is simply intended to accelerate the process, you can find more info [https://github.com/liangyuxin42/SimCSE-reproduce/blob/main/dataset-prepare.ipynb](here)

**Comment by Zi-hao-Wei** [comment]
Thanks a lot.
