### ISSUE TITLE
offline branch代码中好像没看到stop grad操作

### ISSUE THREAD

**Issue by tianylin98** [xbdxwyh/mocose#2]
hi，看了下mocose.py中的实现，貌似在样本过offline encoder的时候，没有使用no_grad或者detach，是否和文章中的描述有差别呢？

**Comment by xbdxwyh** [comment]
> hi，看了下mocose.py中的实现，貌似在样本过offline encoder的时候，没有使用no_grad或者detach，是否和文章中的描述有差别呢？

你好！
停止梯度更新的代码细节在mocose_demo.ipynb文件里，step 1.3.里面实现的，
```
non_optimizer_list = [model.target_encoder,model.target_pooler]
for layer in non_optimizer_list:
    for para in layer.parameters():
        para.requires_grad = False
```
这里设置了offline encoder（也就是target_encoder）里面的参数requires_grad = False，是通过这样的操作实现no_grad。

**Comment by tianylin98** [comment]
哦哦，谢谢回复！
