### ISSUE TITLE
Will negative samples involve the input sentence?

### ISSUE THREAD

**Issue by Rachel-Yeah-Lee** [xbdxwyh/mocose#3]
Hi, thanks for sharing the great work!
I am wondering that if the negative samples are randomly sample from the training data, will it possibly involves the input sentence?

**Comment by xbdxwyh** [comment]
The training data for each batch is randomly selected, and the queue is updated in the order of selection first-in-first-out, but this does not guarantee that there are duplicate entries in the data to interfere with this. The data we use is consistent with the previous work.

**Comment by Rachel-Yeah-Lee** [comment]
Thanks for your instruction!
And if it is in the first iteration of training, the queue will be randomly initialized with the size of 128 negative samples, right? In this way, will the negative samples possibly contain the training input and cause the duplication?

**Comment by xbdxwyh** [comment]
The initial 128 negative samples are randomly generated values rather than randomly selected negative pieces, which does not lead to duplicating negative examples. In addition, these random values are quickly replaced and are used only once during the entire training.

**Comment by Rachel-Yeah-Lee** [comment]
Thanks for your explanation, can you show me where the code that inital 128 negative samples is?

**Comment by AdamRain** [comment]
Hi, please refer here:
https://github.com/xbdxwyh/mocose/blob/45cbc8105253b969541e8a4ae2e27753d98f9966/mocose.py#L309

**Comment by Rachel-Yeah-Lee** [comment]
Thanks a lot!
